### ISSUE TITLE
"Invalid endpoint: s3.amazonaws.com"

### ISSUE THREAD

**Issue by gnestor** [danielfrg/s3contents#12]
I'm running into the following error when trying to use s3contents inside of the [tensorflow-notebook](https://github.com/jupyter/docker-stacks/tree/master/tensorflow-notebook) Docker image. My config matches the example:

```py
from s3contents import S3ContentsManager

c = get_config()

# Tell Jupyter to use S3ContentsManager for all storage.
c.NotebookApp.contents_manager_class = S3ContentsManager
c.S3ContentsManager.access_key_id = <AWS Access Key ID / IAM Access Key ID>
c.S3ContentsManager.secret_access_key = <AWS Secret Access Key / IAM Secret Access Key>
c.S3ContentsManager.bucket_name = "<>"
```

The stack trace:

```
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-notebook", line 6, in <module>
    sys.exit(notebook.notebookapp.main())
  File "/opt/conda/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 1294, in initialize
    self.init_configurables()
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 1038, in init_configurables
    log=self.log,
  File "/opt/conda/lib/python3.5/site-packages/s3contents/s3manager.py", line 44, in __init__
    delimiter=self.delimiter
  File "/opt/conda/lib/python3.5/site-packages/s3contents/s3fs.py", line 40, in __init__
    config=config
  File "/opt/conda/lib/python3.5/site-packages/boto3/__init__.py", line 83, in client
    return _get_default_session().client(*args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/opt/conda/lib/python3.5/site-packages/botocore/session.py", line 836, in create_client
    client_config=config, api_version=api_version)
  File "/opt/conda/lib/python3.5/site-packages/botocore/client.py", line 70, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/opt/conda/lib/python3.5/site-packages/botocore/client.py", line 224, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/opt/conda/lib/python3.5/site-packages/botocore/args.py", line 71, in get_client_args
    timeout=(new_config.connect_timeout, new_config.read_timeout))
  File "/opt/conda/lib/python3.5/site-packages/botocore/endpoint.py", line 272, in create_endpoint
    raise ValueError("Invalid endpoint: %s" % endpoint_url)
ValueError: Invalid endpoint: s3.amazonaws.com
```

**Comment by gnestor** [comment]
I just resolved this by setting prepending a `https://` to the default endpoint URL:

```py
c.S3ContentsManager.endpoint_url = 'https://s3.amazonaws.com'
```

From the [boto docs](https://boto3.readthedocs.io/en/latest/reference/core/session.html#boto3.session.Session.client):

> The complete URL to use for the constructed client. Normally, botocore will automatically construct the appropriate URL to use when communicating with a service. You can specify a complete URL (including the "http/https" scheme) to override this behavior. If this value is provided, then use_ssl is ignored.

**Comment by danielfrg** [comment]
Ah yes, thanks for the report! I have fixed the default value to include `https://` so hopefully less people will get into this error.

Thanks.

**Comment by gnestor** [comment]
Thanks @danielfrg!
