### ISSUE TITLE
Error when upgrading to 0.6.3

### ISSUE THREAD

**Issue by pvanliefland** [danielfrg/s3contents#122]
Hello!

I tried upgrading to version 0.6.3 but it doesn't seem to work. I have attached the full stack trace below.

I think it has to with two incompatible changes in `s3contents` (https://github.com/danielfrg/s3contents/pull/121) and `fsspec` (https://github.com/intake/filesystem_spec/pull/572).

In the meantime, I have pinned `s3contents`, `s3fs` and `fsspec` to previous versions (`0.6.0` for `s3contents`) and it's working again.

Have a nice day,

Pierre

```bash
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/opt/conda/lib/python3.8/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/opt/conda/lib/python3.8/site-packages/notebook/services/contents/handlers.py", line 111, in get
    model = yield maybe_future(self.contents_manager.get(
  File "/opt/conda/lib/python3.8/site-packages/hybridcontents/api_utils.py", line 61, in wrapped
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/hybridcontents/hybridmanager.py", line 225, in get
    return self.__get(path, content=content, type=type, format=format)
  File "/opt/conda/lib/python3.8/site-packages/hybridcontents/hybridmanager.py", line 87, in _wrapper
    result = getattr(mgr, mname)(mgr_path, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/s3contents/genericmanager.py", line 129, in get
    return func(path=path, content=content, format=format)
  File "/opt/conda/lib/python3.8/site-packages/s3contents/genericmanager.py", line 138, in _get_directory
    return self._directory_model_from_path(path, content=content)
  File "/opt/conda/lib/python3.8/site-packages/s3contents/genericmanager.py", line 189, in _directory_model_from_path
    files_s3_detail = sync(self.fs.fs.loop, self.fs.fs._lsdir, prefixed_path)
AttributeError: 'S3FileSystem' object has no attribute 'loop'
```

**Comment by nikhil-oss** [comment]
Hello! 
I am also getting the same error, was there any solution for this ?

Thanks,
Nikhil

**Comment by nikhil-oss** [comment]
@pvanliefland can I know what version combination worked for you?
I tried many and not able to make it work.
Below are my current versions that are not working.
fsspec==0.8.2
s3contents==0.6.3
s3fs==0.4.2

**Comment by danielfrg** [comment]
I will make a release today with new unpinned dependencies so this will be fixed. Hopefully s3fs will not break their API again :D

**Comment by ayush-san** [comment]
I am facing the same issue on 0.7.0
```
fsspec==2021.8.1
s3contents==0.7.0
s3fs==0.4.2
```
