### ISSUE TITLE
SingleUser start up error

### ISSUE THREAD

**Issue by jasondavindev** [danielfrg/s3contents#142]
I'm using Jupyterhub + KubeSpawner for my workload. When I launch the container I face the error

```
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/opt/conda/lib/python3.9/site-packages/tornado/gen.py", line 234, in wrapper
        yielded = ctx_run(next, result)
      File "/opt/conda/lib/python3.9/site-packages/notebook/services/contents/handlers.py", line 116, in get
        model = yield maybe_future(self.contents_manager.get(
      File "/opt/conda/lib/python3.9/site-packages/s3contents/genericmanager.py", line 125, in get
        if path.startswith(self.parent.root_dir):
    AttributeError: 'SingleUserNotebookApp' object has no attribute 'root_dir'
```

I tried with options but the error remains
```
--NotebookApp.root_dir=
--SingleUserNotebookApp.root_dir=
--ServerApp.root_dir=
```

**Comment by burakovsky** [comment]
I have a similar problem when run Classic Jupyter Notebook:
```
Traceback (most recent call last):
      File "/home/lyte/.local/lib/python3.8/site-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/home/lyte/.local/lib/python3.8/site-packages/tornado/gen.py", line 234, in wrapper
        yielded = ctx_run(next, result)
      File "/home/lyte/.local/lib/python3.8/site-packages/notebook/services/contents/handlers.py", line 111, in get
        model = yield maybe_future(self.contents_manager.get(
      File "/home/lyte/.local/lib/python3.8/site-packages/s3contents/genericmanager.py", line 126, in get
        if path.startswith(self.parent.root_dir):
    AttributeError: 'NotebookApp' object has no attribute 'root_dir'
```
It looks like `root_dir` is only JupyterLab config option (according to documentation it was added as a substitute for `notebook_dir`), because when I added `c.NotebookApp.root_dir = ""` parameter I saw this warning message in logs:
```
Config option `root_dir` not recognized by `NotebookApp`.  Did you mean `notebook_dir`?
```

I fixed it by removing [this JupyterLab workaround](https://github.com/danielfrg/s3contents/blob/main/s3contents/genericmanager.py#L123-L132)

**Comment by djuarezg** [comment]
Any news on this?

**Comment by djuarezg** [comment]
@jasondavindev When I try to to run this with an image that in theory only has Python 3.10, when it spawns the Docker container without the lines you mentioned, and I try to save a file, I get the following (which refers to a Python 3.9 path for some reason):

```
[D 2023-05-01 14:50:32.064 SingleUserNotebookApp s3_fs:155] S3contents.S3FS: `test-bucket-ignore/Untitled6.ipynb` is a file: True
[D 2023-05-01 14:50:32.064 SingleUserNotebookApp genericmanager:103] S3contents.GenericManager.file_exists: ('/Untitled7.ipynb')
[D 2023-05-01 14:50:32.064 SingleUserNotebookApp s3_fs:296] S3FS.remove_prefix: self.prefix_: test-bucket-ignore path: ['/Untitled7.ipynb']
[D 2023-05-01 14:50:32.065 SingleUserNotebookApp s3_fs:155] S3contents.S3FS: `test-bucket-ignore/Untitled7.ipynb` is a file: False
[D 2023-05-01 14:50:32.065 SingleUserNotebookApp genericmanager:108] S3contents.GenericManager.dir_exists: path('/Untitled7.ipynb')
[D 2023-05-01 14:50:32.065 SingleUserNotebookApp s3_fs:296] S3FS.remove_prefix: self.prefix_: test-bucket-ignore path: ['/Untitled7.ipynb']
[D 2023-05-01 14:50:32.065 SingleUserNotebookApp s3_fs:163] S3contents.S3FS: `test-bucket-ignore/Untitled7.ipynb` is a directory: False
[D 2023-05-01 14:50:32.067 SingleUserNotebookApp genericmanager:342] save with path=Untitled7.ipynb, model={'type': 'notebook', 'content': {'nbformat': 4, 'nbformat_minor': 5, 'metadata': {}, 'cells': []}, 'format': 'json'}
[D 2023-05-01 14:50:32.067 SingleUserNotebookApp genericmanager:352] S3contents.GenericManager.save {'type': 'notebook', 'content': {'nbformat': 4, 'nbformat_minor': 5, 'metadata': {}, 'cells': []}, 'format': 'json'}: 'Untitled7.ipynb'
[I 2023-05-01 14:50:32.076 SingleUserNotebookApp sign:399] Writing notebook-signing key to /home/jovyan/.local/share/jupyter/notebook_secret
[D 2023-05-01 14:50:32.079 SingleUserNotebookApp s3_fs:296] S3FS.remove_prefix: self.prefix_: test-bucket-ignore path: Untitled7.ipynb
[D 2023-05-01 14:50:32.079 SingleUserNotebookApp s3_fs:296] S3FS.remove_prefix: self.prefix_: test-bucket-ignore path: ['Untitled7.ipynb']
[D 2023-05-01 14:50:32.079 SingleUserNotebookApp s3_fs:275] S3contents.S3FS: Writing notebook: `test-bucket-ignore/Untitled7.ipynb`
[D 2023-05-01 14:50:32.090 SingleUserNotebookApp genericmanager:115] S3contents.GenericManager.get: path('Untitled7.ipynb') type(notebook) format(None)
SingleUserNotebookApp - ERROR - Uncaught exception POST /user/djuarezg/api/contents?1682952631996 (172.23.72.25)
HTTPServerRequest(protocol='https', host='example.com', method='POST', uri='/user/djuarezg/api/contents?1682952631996', version='HTTP/1.1', remote_ip='172.23.72.25')
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/opt/conda/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/notebook/services/contents/handlers.py", line 202, in post
    yield self._new_untitled(path, type=type, ext=ext)
  File "/opt/conda/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/conda/lib/python3.9/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/opt/conda/lib/python3.9/site-packages/notebook/services/contents/handlers.py", line 154, in _new_untitled
    model = yield maybe_future(self.contents_manager.new_untitled(path=path, type=type, ext=ext))
  File "/opt/conda/lib/python3.9/site-packages/notebook/services/contents/manager.py", line 397, in new_untitled
    return self.new(model, path)
  File "/opt/conda/lib/python3.9/site-packages/notebook/services/contents/manager.py", line 423, in new
    model = self.save(model, path)
  File "/opt/conda/lib/python3.9/site-packages/s3contents/genericmanager.py", line 378, in save
    model = self.get(path, type=model["type"], content=False)
  File "/opt/conda/lib/python3.9/site-packages/s3contents/genericmanager.py", line 125, in get
    if path.startswith(self.parent.root_dir):
AttributeError: 'SingleUserNotebookApp' object has no attribute 'root_dir'
[W 2023-05-01 14:50:32.092 SingleUserNotebookApp handlers:617] Unhandled error
```

Any idea on what I could be doing wrong?

PS: When running the container manually I see that `/opt/conda/lib/python3.10/site-packages/s3contents/genericmanager.py` has the `.py` content modified. I also deleted the corresponding `.pyc` file as well just in case.
