### ISSUE TITLE
Getting 'S3ContentsManager' is not defined 

### ISSUE THREAD

**Issue by sharmalalit** [danielfrg/s3contents#2]
I have installed the package using:
```
pip install s3contents

When running the notebook getting following error : 
[E 06:24:06.221 NotebookApp] Exception while loading config file /home/jovyan/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 557, in _load_config_files
        config = loader.load_config()
      File "/opt/conda/lib/python3.5/site-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/opt/conda/lib/python3.5/site-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/opt/conda/lib/python3.5/site-packages/ipython_genutils/py3compat.py", line 185, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "/home/jovyan/.jupyter/jupyter_notebook_config.py", line 43, in <module>
        c.NotebookApp.contents_manager_class = S3ContentsManager
    NameError: name 'S3ContentsManager' is not defined
```

**Comment by sharmalalit** [comment]
I missed the import in config.py but even after doing that I got error related to missing 'nose' packpip3 install nose did help.

**Comment by sharmalalit** [comment]
Also, I noticed that c.S3ContentsManager.endpoint_url is not optional.

**Comment by danielfrg** [comment]
I added `nose` as a requirement in `0.1.1` I think that should fix it.
