### ISSUE TITLE
Exception raised when renaming a notebook

### ISSUE THREAD

**Issue by michailsal** [danielfrg/s3contents#20]
I am getting an exception whenever I try to rename a notebook, is this a known issue?

```
Traceback (most recent call last): File "/opt/conda/lib/python3.6/site-packages/notebook/base/handlers.py", line 516, in wrapper result = yield gen.maybe_future(method(self, *args, **kwargs)) File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run value = future.result() File "/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result raise_exc_info(self._exc_info) File "<string>", line 4, in raise_exc_info File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper yielded = next(result) File "/opt/conda/lib/python3.6/site-packages/notebook/services/contents/handlers.py", line 142, in patch model = yield gen.maybe_future(cm.update(model, path)) File "/opt/conda/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 254, in update self.rename(path, new_path) File "/opt/conda/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 242, in rename self.rename_file(old_path, new_path) File "/opt/conda/lib/python3.6/site-packages/s3contents/s3manager.py", line 259, in rename_file self.s3fs.mv(old_path, new_path) File "/opt/conda/lib/python3.6/site-packages/s3contents/s3fs.py", line 116, in mv self.cp(old_path, new_path) File "/opt/conda/lib/python3.6/site-packages/s3contents/s3fs.py", line 121, in cp if self.isdir(old_path): File "/opt/conda/lib/python3.6/site-packages/s3contents/s3fs.py", line 110, in isdir objs = list(self.bucket.objects.filter(Prefix=key)) File "/opt/conda/lib/python3.6/site-packages/boto3/resources/collection.py", line 83, in __iter__ for page in self.pages(): File "/opt/conda/lib/python3.6/site-packages/boto3/resources/collection.py", line 166, in pages for page in pages: File "/opt/conda/lib/python3.6/site-packages/botocore/paginate.py", line 249, in __iter__ response = self._make_request(current_kwargs) File "/opt/conda/lib/python3.6/site-packages/botocore/paginate.py", line 326, in _make_request return self._method(**current_kwargs) File "/opt/conda/lib/python3.6/site-packages/botocore/client.py", line 312, in _api_call return self._make_api_call(operation_name, kwargs) File "/opt/conda/lib/python3.6/site-packages/botocore/client.py", line 601, in _make_api_call raise error_class(parsed_response, operation_name) botocore.exceptions.ClientError: An error occurred (InternalError) when calling the ListObjects operation (reached max retries: 4): We encountered an internal error. Please try again```

**Comment by danielfrg** [comment]
No, it should work. The tests here are the same as the Jupyter test suite and rename is tested.

Can you paste a better error message (one line makes it hard to read) and some instructions on how to reproduce?

**Comment by michailsal** [comment]
1) I am not using "s3v4" signature version, but instead "s3". My S3 storage still supports the old signature. 

2) I simply create a notebook and then try to rename it to something meaningful e,g, from the default name **Untitled1** to **mynotebook**

3) The first error line is "[E 05:20:44.849 NotebookApp] Unhandled error in API request" and consequently the stacktrace shown above. In one line this is it "botocore.exceptions.ClientError: An error occurred (InternalError) when calling the ListObjects operation (reached max retries: 4): We encountered an internal error. Please try again."

**Comment by danielfrg** [comment]
This is fixed at least on my tests on the latest version.
