### ISSUE TITLE
Exception after upgrading from 0.1.4 to 0.2.0

### ISSUE THREAD

**Issue by nsalmon** [danielfrg/s3contents#26]
After upgrading s3contents from 0.1.4 to 0.2.0, I am getting Exception below, on Jupyter startup.
I have tired installing nose package, but getting a different Exception then.

**Content of my jupyter_notebook_config.py**

 ```import

 os
from s3contents import S3ContentsManager

c = get_config()

# Tell Jupyter to use S3ContentsManager for all storage.
c.NotebookApp.contents_manager_class = S3ContentsManager
c.S3ContentsManager.bucket_name = os.environ['AWS_BUCKET_NAME']`
```

**Exception thrown on startup** 
```jupyter-notebook_1  | [E 15:58:24.728 NotebookApp] Exception while loading config file /home/jovyan/.jupyter/jupyter_notebook_config.py
jupyter-notebook_1  |     Traceback (most recent call last):
jupyter-notebook_1  |       File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 562, in _load_config_files
jupyter-notebook_1  |         config = loader.load_config()
jupyter-notebook_1  |       File "/opt/conda/lib/python3.6/site-packages/traitlets/config/loader.py", line 457, in load_config
jupyter-notebook_1  |         self._read_file_as_dict()
jupyter-notebook_1  |       File "/opt/conda/lib/python3.6/site-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
jupyter-notebook_1  |         py3compat.execfile(conf_filename, namespace)
jupyter-notebook_1  |       File "/opt/conda/lib/python3.6/site-packages/ipython_genutils/py3compat.py", line 198, in execfile
jupyter-notebook_1  |         exec(compiler(f.read(), fname, 'exec'), glob, loc)
jupyter-notebook_1  |       File "/home/jovyan/.jupyter/jupyter_notebook_config.py", line 2, in <module>
jupyter-notebook_1  |         from s3contents import S3ContentsManager
jupyter-notebook_1  |       File "/opt/conda/lib/python3.6/site-packages/s3contents/__init__.py", line 14, in <module>
jupyter-notebook_1  |         from .s3manager import S3ContentsManager
jupyter-notebook_1  |       File "/opt/conda/lib/python3.6/site-packages/s3contents/s3manager.py", line 1, in <module>
jupyter-notebook_1  |         from s3contents.ipycompat import Unicode
jupyter-notebook_1  |       File "/opt/conda/lib/python3.6/site-packages/s3contents/ipycompat.py", line 49, in <module>
jupyter-notebook_1  |         from notebook.services.contents.tests.test_manager import (TestContentsManager)
jupyter-notebook_1  |       File "/opt/conda/lib/python3.6/site-packages/notebook/services/contents/tests/test_manager.py", line 11, in <module>
jupyter-notebook_1  |         from nose import SkipTest
jupyter-notebook_1  |     ModuleNotFoundError: No module named 'nose'
```

**Comment by danielfrg** [comment]
Thanks for letting me know. I just fixed this and released `0.2.1` and its working for me can you paste the other error you get?

**Comment by ericdill** [comment]
This just cropped up for me again. I'm installing s3contents via conda-forge. Digging a bit, seems that nose is listed in the pypi deps in `requirements-package.txt`, but not in the conda-forge recipe. Two things. (1) I suspect that updating the conda-forge recipe to include nose in the runtime requirements is a good idea. (2) Generally speaking, `requirements-package.txt` and the conda-forge runtime requirements should match, right?

**Comment by danielfrg** [comment]
Yep, `nose` is runtime requirement from another dep that doesn't list it so we include it here.
And yes, those two should match.
