### ISSUE TITLE
KeyError using s3content 0.2.1 with s3fs 0.1.3

### ISSUE THREAD

**Issue by kwunlyou** [danielfrg/s3contents#30]
It will have following error. Had a look at the code. It is probably due to the new implementation of [S3FileSystem.info](https://github.com/dask/s3fs/commit/cb4c681b42c7c5eff8e3f56cd11b138a76779c3f#diff-1997c4b809971172b55a040ccbb82ea0). s3fs 0.1.2 works well.

```
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1512, in _execute
        result = yield result
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 307, in wrapper
        yielded = next(result)
      File "/usr/local/lib/python2.7/site-packages/notebook/services/contents/handlers.py", line 112, in get
        path=path, type=type, format=format, content=content,
      File "/usr/local/lib/python2.7/site-packages/s3contents/genericmanager.py", line 86, in get
        return func(path=path, content=content, format=format)
      File "/usr/local/lib/python2.7/site-packages/s3contents/genericmanager.py", line 90, in _get_directory
        return self._directory_model_from_path(path, content=content)
      File "/usr/local/lib/python2.7/site-packages/s3contents/genericmanager.py", line 108, in _directory_model_from_path
        model["content"] = self._convert_file_records(dir_content)
      File "/usr/local/lib/python2.7/site-packages/s3contents/genericmanager.py", line 172, in _convert_file_records
        ret.append(self._file_model_from_path(path, False, None))
      File "/usr/local/lib/python2.7/site-packages/s3contents/genericmanager.py", line 139, in _file_model_from_path
        model["last_modified"] = model["created"] = self.fs.lstat(path)["ST_MTIME"]
      File "/usr/local/lib/python2.7/site-packages/s3contents/s3_fs.py", line 151, in lstat
        ret["ST_MTIME"] = info["LastModified"]
    KeyError: 'LastModified'
```

**Comment by danielfrg** [comment]
Thanks for letting me know. I fixed it by pining s3fs to `0.1.2` and released s3contents `0.2.2` with the fix.
