### ISSUE TITLE
Renaming Folders raises FileNotFoundError when deleting old directory

### ISSUE THREAD

**Issue by pm8k** [danielfrg/s3contents#33]
I'm trying to rename folders in my S3 bucket through the Jupyter interface, but I constantly get this error (sorry for the formatting, the stack trace didn't print pretty in jupyter):

```
Traceback (most recent call last): 
File "/opt/conda/lib/python3.6/site-packages/s3fs/core.py", line 396, in info kwargs, Bucket=bucket, Key=key, **self.req_kw) 
File "/opt/conda/lib/python3.6/site-packages/s3fs/core.py", line 170, in _call_s3 return method(**additional_kwargs)
File "/opt/conda/lib/python3.6/site-packages/botocore/client.py", line 310, in _api_call return self._make_api_call(operation_name, kwargs)
File "/opt/conda/lib/python3.6/site-packages/botocore/client.py", line 599, in _make_api_call raise error_class(parsed_response, operation_name) botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found During handling of the above exception, another exception occurred: 

Traceback (most recent call last): 
File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1415, in _execute result = yield result File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 870, in run value = future.result()
File "/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py", line 215, in result raise_exc_info(self._exc_info)
File "<string>", line 3, in raise_exc_info
File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 230, in wrapper yielded = next(result) File "/opt/conda/lib/python3.6/site-packages/notebook/services/contents/handlers.py", line 125, in patch model = yield gen.maybe_future(cm.update(model, path))
File "/opt/conda/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 295, in update self.rename(path, new_path)
File "/opt/conda/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 283, in rename self.rename_file(old_path, new_path)
File "/opt/conda/lib/python3.6/site-packages/s3contents/genericmanager.py", line 234, in rename_file self.fs.mv(old_path, new_path)
File "/opt/conda/lib/python3.6/site-packages/s3contents/s3_fs.py", line 108, in mv self.rm(old_path)
File "/opt/conda/lib/python3.6/site-packages/s3contents/s3_fs.py", line 131, in rm self.fs.rmdir(path_ + self.delimiter, recursive=True)
File "/opt/conda/lib/python3.6/site-packages/s3fs/core.py", line 641, in rmdir if (key and self.info(path)['Size'] == 0) or not key:
File "/opt/conda/lib/python3.6/site-packages/s3fs/core.py", line 402, in info raise FileNotFoundError(path) FileNotFoundError: mybucket/Untitled Folder/
```
I first thought it might have been the space in 'Untitled Folder' but it errors out even without the space. I'm trying to find out now what is causing it exactly but i'm not familiar with the s3fs package.

**Comment by pm8k** [comment]
After experimenting a bit, it seems s3fs's `rmdir` function does a check with its `info` function that can't be applied to directories [as seen here](https://github.com/dask/s3fs/blob/master/s3fs/core.py#L703). Running this on a directory path raises the same error. However, using the base `rm` function produces the desired effect since it can be applied to directories as well.

**Comment by AbdealiJK** [comment]
Is there any fix or workaround for this ?
I seem to be unable to show this to my team because of this issue :)

**Comment by pm8k** [comment]
I have been using this successfully using a forked version for our current build, using the change I recommended above: https://github.com/pm8k/s3contents

I've been meaning to revisit it to ensure this is the desired behavior and submit a PR, since it should be a simple change.

**Comment by AbdealiJK** [comment]
@danielfrg looks like a one word change =D

https://github.com/pm8k/s3contents/commit/cb219e60ff2b9bfbf208cf046033b30836cea500

Can we get this pushed upstream to this repo?

**Comment by pm8k** [comment]
Looks like this was fixed in June, so I'm closing this PR
