### ISSUE TITLE
Launching Error while Opening a text file from Jupyter UI from the s3 location

### ISSUE THREAD

**Issue by mangeshkaslikar** [danielfrg/s3contents#52]
Hi, 

I have configured Jupyter Notebook with S3 and using the S3ContentsManager. When i goto the s3 folder (from the Jupyter UI) and click on a Text file / Diagram File tile, i get a prompt saying -> Unable to Load File, Launcher Error. I also noticed logs from stderr. Pasting Stack Trace here : 

	[E 02:40:05.537 LabApp] Uncaught exception GET /
	path/to/jupyter/api/contents/s3/untitled.txt?format=text&type=file&content=1&1541472005430 (<SomeIP>)
		HTTPServerRequest(protocol='https', host='<HostName>', method='GET', uri='/path/to/jupyter/api/contents/s3/untitled.txt?format=text&type=file&content=1&1541472005430', version='HTTP/1.1', remote_ip='<SomeIP>')
		Traceback (most recent call last):
		  File "/opt/conda/lib/python3.6/site-packages/urllib3/response.py", line 331, in _error_catcher
			yield
		  File "/opt/conda/lib/python3.6/site-packages/urllib3/response.py", line 409, in read
			data = self._fp.read()
		  File "/opt/conda/lib/python3.6/http/client.py", line 462, in read
			s = self._safe_read(self.length)
		  File "/opt/conda/lib/python3.6/http/client.py", line 614, in _safe_read
			raise IncompleteRead(b''.join(s), amt)
		http.client.IncompleteRead: IncompleteRead(0 bytes read, 5242880 more expected)

    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
        yielded = next(result)
      File "/opt/conda/lib/python3.6/site-packages/notebook/services/contents/handlers.py", line 112, in 
    get
        path=path, type=type, format=format, content=content,
      File "/opt/conda/lib/python3.6/site-packages/pgcontents/api_utils.py", line 224, in wrapped
        return fn(*args, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/pgcontents/hybridmanager.py", line 235, in get
        return self.__get(path, content=content, type=type, format=format)
      File "/opt/conda/lib/python3.6/site-packages/pgcontents/hybridmanager.py", line 93, in _wrapper
        result = getattr(mgr, mname)(mgr_path, *args, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/s3contents/genericmanager.py", line 86, in get
        return func(path=path, content=content, format=format)
      File "/opt/conda/lib/python3.6/site-packages/s3contents/genericmanager.py", line 98, in _get_file
        return self._file_model_from_path(path, content=content, format=format)
      File "/opt/conda/lib/python3.6/site-packages/s3contents/genericmanager.py", line 144, in _file_model_from_path
        content = self.fs.read(path)
      File "/opt/conda/lib/python3.6/site-packages/s3contents/s3_fs.py", line 152, in read
        content = f.read().decode("utf-8")
      File "/opt/conda/lib/python3.6/site-packages/s3fs/core.py", line 1270, in read
        self._fetch(self.loc, self.loc + length)
      File "/opt/conda/lib/python3.6/site-packages/s3fs/core.py", line 1234, in _fetch
        req_kw=self.s3.req_kw)
      File "/opt/conda/lib/python3.6/site-packages/s3fs/core.py", line 1439, in _fetch_range
        return resp['Body'].read()
      File "/opt/conda/lib/python3.6/site-packages/botocore/response.py", line 78, in read
        chunk = self._raw_stream.read(amt)
      File "/opt/conda/lib/python3.6/site-packages/urllib3/response.py", line 430, in read
        raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
      File "/opt/conda/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/opt/conda/lib/python3.6/site-packages/urllib3/response.py", line 349, in _error_catcher
        raise ProtocolError('Connection broken: %r' % e, e)
    urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read, 5242880 more expected)', IncompleteRead(0 bytes read, 5242880 more expected))
    [W 02:40:05.538 LabApp] Unhandled error

What seems to be the issue. 

Regards, 
Mangesh

**Comment by danielfrg** [comment]
This was likely fixed on one of the newer versions.
