### ISSUE TITLE
Read/write access to specific user folder

### ISSUE THREAD

**Issue by vishaldesai** [danielfrg/s3contents#64]
Is it possible to configure subfolder level read/write access? So lets say there are two users, user1 and user2. When user1 logs in, user1 can see all notebooks in bucket/user1 and bucket/user2 but have write access only to bucket/user1.

**Comment by danielfrg** [comment]
I think this should be possible by just having IAM different credentials and read/write permissions directly on S3/AWS.

**Comment by vishaldesai** [comment]
I created image using below docker file, created AWS ECS task definition which has IAM role that has access to bucket vishaljupyterhub. But it throws error as shown below.

```
FROM jupyterhub/jupyterhub:latest

RUN echo 'from s3contents import S3ContentsManager' >> /etc/jupyter/jupyter_notebook_config.py
RUN echo 'c = get_config()' >> /etc/jupyter/jupyter_notebook_config.py
RUN echo 'c.NotebookApp.contents_manager_class = S3ContentsManager' >> /etc/jupyter/jupyter_notebook_config.py
RUN echo 'c.S3ContentsManager.bucket = "vishaljuypterhub"' >> /etc/jup
yter/jupyter_notebook_config.py
RUN useradd --create-home user3
RUN echo "user3:user3"|chpasswd
```

Errors:
```
2019-04-22 11:36:32[I 2019-04-22 15:36:32.739 JupyterHub log:174] 200 GET /hub/api/users/user3/server/progress (user3@127.0.0.1) 7735.52ms
2019-04-22 11:36:32[E 2019-04-22 15:36:32.736 JupyterHub gen:593] Exception in Future <Task finished coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py:800> exception=TimeoutError("Server at http://127.0.0.1:53469/user/user3/ didn't respond in 30 seconds",)> after timeout
2019-04-22 11:36:32 Traceback (most recent call last):
2019-04-22 11:36:32 File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 589, in error_callback
2019-04-22 11:36:32 future.result()
2019-04-22 11:36:32 File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 807, in finish_user_spawn
2019-04-22 11:36:32 await spawn_future
2019-04-22 11:36:32 File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 654, in spawn
2019-04-22 11:36:32 await self._wait_up(spawner)
2019-04-22 11:36:32 File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 701, in _wait_up
2019-04-22 11:36:32 raise e
2019-04-22 11:36:32 File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 669, in _wait_up
2019-04-22 11:36:32 http=True, timeout=spawner.http_timeout, ssl_context=ssl_context
2019-04-22 11:36:32 File "/opt/conda/lib/python3.6/site-packages/jupyterhub/utils.py", line 234, in wait_for_http_server
2019-04-22 11:36:32 timeout=timeout,
2019-04-22 11:36:32 File "/opt/conda/lib/python3.6/site-packages/jupyterhub/utils.py", line 177, in exponential_backoff
2019-04-22 11:36:32 raise TimeoutError(fail_message)
2019-04-22 11:36:32 TimeoutError: Server at http://127.0.0.1:53469/user/user3/ didn't respond in 30 seconds
2019-04-22 11:36:32
2019-04-22 11:36:32[W 2019-04-22 15:36:32.738 JupyterHub users:512] Stream closed while handling /hub/api/users/user3/server/progress
2019-04-22 11:36:32[I 2019-04-22 15:36:32.738 JupyterHub log:174] 200 GET /hub/api/users/user3/server/progress (user3@127.0.0.1) 28315.73ms
2019-04-22 11:36:32[W 2019-04-22 15:36:32.713 JupyterHub user:678] user3's server never showed up at http://127.0.0.1:53469/user/user3/ after 30 seconds. Giving up
2019-04-22 11:36:24[I 2019-04-22 15:36:24.877 JupyterHub pages:303] user3 is pending spawn
2019-04-22 11:36:13ERROR:asyncio:Task exception was never retrieved
2019-04-22 11:36:13future: <Task finished coro=<BaseHandler.spawn_single_user() done, defined at /opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py:697> exception=HTTPError()>
2019-04-22 11:36:13Traceback (most recent call last):
2019-04-22 11:36:13 File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 889, in spawn_single_user
2019-04-22 11:36:13 timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future
2019-04-22 11:36:13tornado.util.TimeoutError: Timeout
2019-04-22 11:36:13During handling of the above exception, another exception occurred:
2019-04-22 11:36:13Traceback (most recent call last):
2019-04-22 11:36:13 File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 922, in spawn_single_user
2019-04-22 11:36:13 % (status, spawner._log_name),
2019-04-22 11:36:13tornado.web.HTTPError: HTTP 500: Internal Server Error (Spawner failed to start [status=1]. The logs for user3 may contain details.)
2019-04-22 11:36:04Traceback (most recent call last):
2019-04-22 11:36:04 File "/opt/conda/bin/jupyterhub-singleuser", line 10, in <module>
2019-04-22 11:36:04 sys.exit(main())
2019-04-22 11:36:04 File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 660, in main
2019-04-22 11:36:04 return SingleUserNotebookApp.launch_instance(argv)
2019-04-22 11:36:04 File "/opt/conda/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
2019-04-22 11:36:04 return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
2019-04-22 11:36:04 File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
2019-04-22 11:36:04 app.initialize(argv)
2019-04-22 11:36:04 File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 558, in initialize
2019-04-22 11:36:04 return super().initialize(argv)
2019-04-22 11:36:04 File "</opt/conda/lib/python3.6/site-packages/decorator.py:decorator-gen-7>", line 2, in initialize
2019-04-22 11:36:04 File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
2019-04-22 11:36:04 return method(app, *args, **kwargs)
2019-04-22 11:36:04 File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1628, in initialize
2019-04-22 11:36:04 self.init_configurables()
2019-04-22 11:36:04 File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1324, in init_configurables
2019-04-22 11:36:04 log=self.log,
2019-04-22 11:36:04 File "/opt/conda/lib/python3.6/site-packages/s3contents/s3manager.py", line 52, in __init__
2019-04-22 11:36:04 sse=self.sse)
2019-04-22 11:36:04 File "/opt/conda/lib/python3.6/site-packages/s3contents/s3_fs.py", line 69, in __init__
2019-04-22 11:36:04 self.init()
2019-04-22 11:36:04 File "/opt/conda/lib/python3.6/site-packages/s3contents/s3_fs.py", line 73, in init
2019-04-22 11:36:04 self.ls("")
2019-04-22 11:36:04 File "/opt/conda/lib/python3.6/site-packages/s3contents/s3_fs.py", line 81, in ls
2019-04-22 11:36:04 files = self.fs.ls(path_, refresh=True)
2019-04-22 11:36:04 File "/opt/conda/lib/python3.6/site-packages/s3fs/core.py", line 404, in ls
2019-04-22 11:36:04 raise FileNotFoundError(path)
2019-04-22 11:36:04FileNotFoundError: vishaljuypterhub
```
