### ISSUE TITLE
Dependency on mock module in python2

### ISSUE THREAD

**Issue by Corni** [danielfrg/s3contents#9]
Hi,
when using s3contents on python 2, it requires the mock module, even when no tests are run.
The following error is thrown on startup of jupyter:
```(venv-jupyter)mac-0096:s3contents-github criemenschneider$ jupyter notebook --config=jupyter_config.py --no-browser
[E 16:10:56.517 NotebookApp] Exception while loading config file /Users/criemenschneider/PycharmProjects/s3contents-github/jupyter_config.py
    Traceback (most recent call last):
      File "/Users/criemenschneider/venv-jupyter/lib/python2.7/site-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/Users/criemenschneider/venv-jupyter/lib/python2.7/site-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/Users/criemenschneider/venv-jupyter/lib/python2.7/site-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/Users/criemenschneider/venv-jupyter/lib/python2.7/site-packages/ipython_genutils/py3compat.py", line 290, in execfile
        builtin_mod.execfile(filename, *where)
      File "/Users/criemenschneider/PycharmProjects/s3contents-github/jupyter_config.py", line 1, in <module>
        from s3contents import S3ContentsManager
      File "/Users/criemenschneider/PycharmProjects/s3contents-github/s3contents/__init__.py", line 5, in <module>
        from .s3manager import S3ContentsManager
      File "/Users/criemenschneider/PycharmProjects/s3contents-github/s3contents/s3manager.py", line 8, in <module>
        from s3contents.s3fs import S3FS, S3FSError, NoSuchFile
      File "/Users/criemenschneider/PycharmProjects/s3contents-github/s3contents/s3fs.py", line 9, in <module>
        from s3contents.ipycompat import HasTraits, Unicode
      File "/Users/criemenschneider/PycharmProjects/s3contents-github/s3contents/ipycompat.py", line 64, in <module>
        from notebook.services.contents.tests.test_contents_api import (
      File "/Users/criemenschneider/venv-jupyter/lib/python2.7/site-packages/notebook/services/contents/tests/test_contents_api.py", line 20, in <module>
        from notebook.tests.launchnotebook import NotebookTestBase, assert_http_error
      File "/Users/criemenschneider/venv-jupyter/lib/python2.7/site-packages/notebook/tests/launchnotebook.py", line 18, in <module>
        from mock import patch #py2
    ImportError: No module named mock
[E 16:10:56.655 NotebookApp] Exception while loading config file /Users/criemenschneider/PycharmProjects/s3contents-github/jupyter_config.py
    Traceback (most recent call last):
      File "/Users/criemenschneider/venv-jupyter/lib/python2.7/site-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/Users/criemenschneider/venv-jupyter/lib/python2.7/site-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/Users/criemenschneider/venv-jupyter/lib/python2.7/site-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/Users/criemenschneider/venv-jupyter/lib/python2.7/site-packages/ipython_genutils/py3compat.py", line 290, in execfile
        builtin_mod.execfile(filename, *where)
      File "/Users/criemenschneider/PycharmProjects/s3contents-github/jupyter_config.py", line 1, in <module>
        from s3contents import S3ContentsManager
      File "/Users/criemenschneider/PycharmProjects/s3contents-github/s3contents/__init__.py", line 5, in <module>
        from .s3manager import S3ContentsManager
      File "/Users/criemenschneider/PycharmProjects/s3contents-github/s3contents/s3manager.py", line 8, in <module>
        from s3contents.s3fs import S3FS, S3FSError, NoSuchFile
      File "/Users/criemenschneider/PycharmProjects/s3contents-github/s3contents/s3fs.py", line 9, in <module>
        from s3contents.ipycompat import HasTraits, Unicode
      File "/Users/criemenschneider/PycharmProjects/s3contents-github/s3contents/ipycompat.py", line 64, in <module>
        from notebook.services.contents.tests.test_contents_api import (
      File "/Users/criemenschneider/venv-jupyter/lib/python2.7/site-packages/notebook/services/contents/tests/test_contents_api.py", line 20, in <module>
        from notebook.tests.launchnotebook import NotebookTestBase, assert_http_error
      File "/Users/criemenschneider/venv-jupyter/lib/python2.7/site-packages/notebook/tests/launchnotebook.py", line 18, in <module>
        from mock import patch #py2
    ImportError: No module named mock
[I 16:10:56.773 NotebookApp] Serving notebooks from local directory: /Users/criemenschneider/PycharmProjects/s3contents-github
[I 16:10:56.773 NotebookApp] 0 active kernels
[I 16:10:56.773 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=969bca5897dac46cd0d50ffa04c07da163b730db8259bf1d
[I 16:10:56.773 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

```

I couldn't figure out why pgcontents, where ipycompat.py is borrowed from works, but s3contents does not.

**Comment by danielfrg** [comment]
I added `mock` as a dependency and released `0.1.3` with that and other fixes for Jupyter Notebook 5.0 so I think that should solve the issue.
Please reopen if thats not the case.
